#!/usr/bin/env python3
"""Regenerate INDEX.yaml from SSOT frontmatter."""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import validate


def quote(value: str) -> str:
    if value == "" or any(ch in value for ch in ":#[]{}") or value.strip() != value:
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def main() -> int:
    errors = validate.validate()
    if errors:
        for error in errors:
            print(error)
        print("build_index.py: validation failed; refusing to write INDEX.yaml.", file=sys.stderr)
        return 1

    base = validate.root()
    entries: list[dict[str, str]] = []
    for path, rel in validate.md_files(base):
        data, _ = validate.parse_frontmatter(path.read_text(encoding="utf-8-sig"))
        if not data or not isinstance(data.get("slug"), str):
            continue
        bucket, sub_bucket, role = validate.bucket_for(rel)
        entry = {
            "slug": str(data["slug"]),
            "path": rel,
            "type": str(data.get("type", "")),
            "status": str(data.get("status", "")),
            "last_updated": str(data.get("last_updated", "")),
            "bucket": bucket,
        }
        topic = data.get("topic")
        if isinstance(topic, str) and topic:
            entry["topic"] = topic
        if sub_bucket:
            entry["sub_bucket"] = sub_bucket
        if role:
            entry["role"] = role
        entries.append(entry)

    entries.sort(key=lambda e: e["slug"])
    fields = ("slug", "path", "type", "status", "topic", "last_updated", "bucket", "sub_bucket", "role")
    lines = [
        "# GENERATED by scripts/build_index.py - DO NOT EDIT.",
        f"# Generated {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "entries:",
    ]
    for entry in entries:
        first = True
        for field in fields:
            if field not in entry:
                continue
            prefix = "  - " if first else "    "
            lines.append(f"{prefix}{field}: {quote(entry[field])}")
            first = False
    lines.append("")
    (base / "INDEX.yaml").write_text("\n".join(lines), encoding="utf-8")
    print(f"build_index.py: wrote INDEX.yaml ({len(entries)} entries).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
